language: go

script:
  - go test -race -v ./...

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get gitlab.com/parallelcoin/node/fsnotify
  - go get gopkg.in/tomb.v1
